on:
  workflow_dispatch:

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Ubuntu 24.04 LTS VM
        run: |
          az vm create --resource-group rg-infra-imoc-001 --name myUbuntuVM --image Ubuntu2404 --admin-username azureuser 